INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (2, N'شاورما سوبر                                       ', 2.6, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (3, N'شاورما دبل                                        ', 3, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (4, N'وجبةبرجر                                          ', 4.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (5, N'وجبة زنجر                                         ', 2.75, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (6, N'شاورما اطالي                                      ', 3, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (7, N'فاهيتا                                            ', 2.75, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (8, N'بروستد                                            ', 3.65, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (9, N'دجاج مشوي                                         ', 5, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (10, N'ساندوش شاورما عادي                                ', 0.6, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (11, N'ساندوش شاورما سوبر                                ', 1.2, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (12, N'ساندوش كباب                                       ', 1, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (13, N'برجر لحم                                          ', 3.5, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (14, N'زنجر فرنسي                                        ', 1.5, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (15, N'بيتزا صغير                                        ', 3, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (16, N'بيتزا وسط                                         ', 5, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (17, N'بيتزا كبير                                        ', 7, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (18, N'معجنات زعتر                                       ', 0.75, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (19, N'معجنات بيض                                        ', 1, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (20, N'معجنات جبنة بيضاء                                 ', 1.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (21, N'ماتركس كولا                                       ', 0.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (22, N'ماتركس برتقال                                     ', 0.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (23, N'ماتركس ليمون                                      ', 0.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (24, N'كوكتيل فواكه                                      ', 1.5, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (25, N'مياه معدنية                                       ', 0.25, 0, 0)
INSERT INTO [dbo].[restorant3] ([Id], [name], [price], [num_sales], [profit]) VALUES (1, N'شاورما عادي                                       ', 2, 0, 0)
